version: '3'

services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - VERSION=docker
    volumes:
      - ${PLEX_CONFIG_DIR}:/config
      - ${MEDIA_DIR}/TV:/tv
      - ${MEDIA_DIR}/Movies:/movies
    ports:
      - ${PLEX_PORT}:32400
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    volumes:
      - ${RADARR_CONFIG_DIR}:/config
      - ${MOVIES_DIR}:/movies
      - ${DOWNLOADS_DIR_COMPLETE}:/downloads
    ports:
      - ${RADARR_PORT}:7878
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    volumes:
      - ${SONARR_CONFIG_DIR}:/config
      - ${TV_DIR}:/tv
      - ${DOWNLOADS_DIR_COMPLETE}:/downloads
    ports:
      - ${SONARR_PORT}:8989
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    volumes:
      - ${TRANSMISSION_CONFIG_DIR}:/config
      - ${DOWNLOADS_DIR_INCOMPLETE}:/downloads
    ports:
      - ${TRANSMISSION_PORT}:9091
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd
    volumes:
      - ${SABNZBD_CONFIG_DIR}:/config
      - ${DOWNLOADS_DIR_INCOMPLETE}:/downloads
    ports:
      - ${SABNZBD_PORT}:8080
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    volumes:
      - ${JACKETT_CONFIG_DIR}:/config
      - ${DOWNLOADS_DIR_COMPLETE}:/downloads
    ports:
      - ${JACKETT_PORT}:9117
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    volumes:
      - ${PORTAINER_CONFIG_DIR}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORTAINER_PORT}:9000
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 300
