version: '3'

services:

  plex:
    image: linuxserver/plex
    volumes:
      - ${PLEX_CONFIG_DIR}:/config
      - ${MEDIA_DIR}:/media
    ports:
      - 32400:32400
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

  radarr:
    image: linuxserver/radarr
    volumes:
      - ${RADARR_CONFIG_DIR}:/config
      - ${MOVIES_DIR}:/movies
      - ${DOWNLOADS_DIR_COMPLETE}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    volumes:
      - ${SONARR_CONFIG_DIR}:/config
      - ${TV_DIR}:/tv
      - ${DOWNLOADS_DIR_COMPLETE}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    volumes:
      - ${TRANSMISSION_CONFIG_DIR}:/config
      - ${DOWNLOADS_DIR_INCOMPLETE}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd
    volumes:
      - ${SABNZBD_CONFIG_DIR}:/config
      - ${DOWNLOADS_DIR_INCOMPLETE}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    volumes:
      - ${JACKETT_CONFIG_DIR}:/config
      - ${DOWNLOADS_DIR_COMPLETE}:/downloads
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped